spring:
  application:
     name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce

keycloak:
  realm: ecommerce
  auth-server-url: http://localhost:8080
  client-id: ecommerce-app
  client-secret: 6DWka4kF7cbwFjHyBwWxlZJUi0uu3lfS
  admin-username: admin
  admin-password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: user-service
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

server:
  port: 8090